CREATE TABLE Users(
	Id INT AUTO_INCREMENT PRIMARY KEY,
	APIKey varchar(36) NULL,
	Username VARCHAR(50) NOT NULL,
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL,
	PasswordHash VARCHAR(100) NOT NULL,
	IsEmailConfirmed TINYINT  NOT NULL,
	ModifiedOn DATETIME(3) NULL,
	ModifiedBy VARCHAR(50) NULL,
	CreatedOn DATETIME(3) NOT NULL,
	CreatedBy VARCHAR(50) NULL,
	ResetToken VARCHAR(1000),
	ResetTokenExpired DATETIME(3) NULL
) ENGINE=INNODB;