import { Component } from '@angular/core';
import { MatIconRegistry } from "@angular/material/icon";
import { DomSanitizer } from '@angular/platform-browser';


@Component({
  selector: 'app-root',
  template: '<router-outlet></router-outlet>',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'The Growth Tree';
  
  constructor(private matIconRegistry: MatIconRegistry, private domSanitizer: DomSanitizer){
    matIconRegistry.addSvgIcon(
      "tgt_add_user",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/add-user.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_back",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/back-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_bell",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/bell-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_bell_active",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/bell-active.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_bookmark",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/bookmark-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_business_plan",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/business-plan-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_check",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/check-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_check_rounded",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/tgt_check_rounded.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_cross_rounded",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/tgt_cross_rounded.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_clipboard",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/clipboard-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_close",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/close-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_collaboration",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/collaboration-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_company",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/company-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_consultant",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/noun_consultant.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_document",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/document-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_certificate",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/noun-document-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_human_resource",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/human-resource-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_dashboard",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/dashboard-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_delete",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/delete-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_download",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/download-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_edit",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/edit-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_filter",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/filter-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_finance",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/finance-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_financial_document",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/financial-document-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_folder",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/folder-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_graduation",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/graduation-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_hanging_whiteboard",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/hanging-whiteboard-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_help",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/help-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_http_link",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/http-link.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_idea",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/idea-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_invest",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/invest-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_investment",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/investment-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_left_arrow",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/left-arrow-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_legal",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/legal-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_marketing",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/marketing-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_mentor",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/mentor-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_error_exclamation",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/error-exclamation-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_path_right",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/path-right-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_path_left",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/path-left-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_pie_chart",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/pie-chart-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_play_button",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/play-button-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_plus",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/plus-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_processing",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/processing-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_profile",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/profile-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_profit_and_loss",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/profit-and-loss-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_question",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/question-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_recycle",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/recycle-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_right_arrow",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/right-arrow-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_search",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/search-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_service_providers",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/service-providers-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_settings",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/settings-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_share",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/share-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_status",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/status-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_team",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/team-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_tick",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/tick-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_up_arrow",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/up-arrow-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_user_account",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/user-account-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_user",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/user-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_nda",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/nda-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_privacy",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/privacy-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_simplicity",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/simplicity-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_transperancy",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/transperancy-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_trust",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/trust-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_dollar",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/dollar-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_money",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/money-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_time",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/time-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_analysis_report",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/analysis-report-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_multiple_line_graph",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/multiple-line-graph-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_presentation",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/presentation-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_return_investment",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/return-of-investment-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_noun_business_plan",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/noun-business-plan-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_noun_financial_document",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/noun-financial-document-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_noun_invest",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/noun-invest-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_noun_pie_chart",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/noun-pie-chart-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_noun_profit_loss",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/noun-profit-loss-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_noun_team",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/noun-team-icon.svg")
      );
    matIconRegistry.addSvgIcon(
      "tgt_investments",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/noun_investment.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_university",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/university-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_calendar",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/calendar-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_copy",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/copy.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_more",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/more.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_world",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/noun_world.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_submit_arrow",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/submit-arrow.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_triangle",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/triangle-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_circular_pie_chart",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/circular-pie-chart.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_accordion_closed",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/accordion-closed-icon.svg")
    );
    matIconRegistry.addSvgIcon(
      "tgt_accordion_opened",
      domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/accordion-opened-icon.svg")
    );
  }
}
